AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9
  gpt-transcriber PoC

Resources:
  # Lambda(Engine)
  GPTApiClient:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 900
      MemorySize: 2048
      Architectures:
        - arm64
      Events:
        ApiRoot:
          Type: Api
          Properties:
            Path: '/'
            Method: GET
            RestApiId: !Ref HandlerApi
        ApiProxy:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: GET
            RestApiId: !Ref HandlerApi

  # API Gateway
  HandlerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev

